# apiVersion: v1
# kind: Service
# metadata:
#   name: myapp-service
# spec:
#   type: ClusterIP
#   ports:
#     - name: http
#       protocol: TCP
#       port: 400
#       targetPort: 4000
#   selector:
#     app: myapp

apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: ClusterIP
  # clusterIp: 10.96.0.1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: myapp
# create service
# kubectl create -f service.yml